/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.presentation;

import javax.swing.DefaultComboBoxModel;
import quiz.businesslogic.QuizManager;

/**
 *
 * @author Gregor
 */
public class QuizGUI extends javax.swing.JFrame
{
    
    QuizManager manager;
    DefaultComboBoxModel<String> comboboxModel;

    /**
     * Creates new form QuizGUI
     *
     * @param manager
     */
    public QuizGUI(QuizManager manager)
    {
        this.manager = manager;
        initComponents();
        vulVraagIn();
        vulAndwoordenIn();
        this.textarea_opmerkingenVeld.setText("Nog geen andwoord gegeven.");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        label_vraagLabel = new javax.swing.JLabel();
        label_vraag = new javax.swing.JLabel();
        button_bevestigKnop = new javax.swing.JButton();
        combobox_andwoorden = new javax.swing.JComboBox();
        label_andwoordLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_opmerkingenVeld = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 800));

        jPanel1.setMinimumSize(new java.awt.Dimension(382, 247));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 360));

        label_vraagLabel.setText("Welk character is de hoofdpersoon in de anime:");

        label_vraag.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_vraag.setText(" ");

        button_bevestigKnop.setText("OK");
        button_bevestigKnop.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                button_bevestigKnopActionPerformed(evt);
            }
        });

        label_andwoordLabel.setText("Andwoord:");

        textarea_opmerkingenVeld.setColumns(20);
        textarea_opmerkingenVeld.setRows(5);
        jScrollPane1.setViewportView(textarea_opmerkingenVeld);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(label_vraagLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(label_vraag, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(label_andwoordLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .add(combobox_andwoorden, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(41, 41, 41)
                                .add(button_bevestigKnop)
                                .addContainerGap(40, Short.MAX_VALUE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(label_vraagLabel)
                    .add(label_vraag))
                .add(46, 46, 46)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(combobox_andwoorden, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(label_andwoordLabel)
                    .add(button_bevestigKnop))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(466, 289));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void button_bevestigKnopActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_button_bevestigKnopActionPerformed
    {//GEN-HEADEREND:event_button_bevestigKnopActionPerformed
        String andwoord = combobox_andwoorden.getSelectedItem().toString();
        if (manager.checkAndwoord(andwoord))
        {
            textarea_opmerkingenVeld.setText("Het andwoord is goed.");
        }
        else
        {
            textarea_opmerkingenVeld.setText("Het andwoord is fout. \n\nHet juiste andwoord was:\n" + manager.getCorrectAndwoord());
        }
    }//GEN-LAST:event_button_bevestigKnopActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_bevestigKnop;
    private javax.swing.JComboBox combobox_andwoorden;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_andwoordLabel;
    private javax.swing.JLabel label_vraag;
    private javax.swing.JLabel label_vraagLabel;
    private javax.swing.JTextArea textarea_opmerkingenVeld;
    // End of variables declaration//GEN-END:variables

    private void vulVraagIn()
    {
        label_vraag.setText(manager.getVraag());
    }
    
    private void vulAndwoordenIn()
    {
        comboboxModel = new DefaultComboBoxModel(manager.getAndwoorden().toArray());
        combobox_andwoorden.setModel(comboboxModel);
    }
}
